### ISSUE TITLE
[New functions]

### ISSUE THREAD

**Issue by LucaFlash** [vipexv/minimal-hud#6]
Hi, I have some advice to implement

- Voice icon for pma-voice
- Player ID
- Logo top right
- Put the possibility that if I have different hp put the number of hp

Plus there is a problem that fivem below 100 hp instantly kills the player
So the life bar logic could be improved

**Comment by vipexv** [comment]
I believe the script already accounts for the health thingy since GTA Is weird and has their health 100-200 Which should be getting calculated/handled within the loop, and the other ideas or nice its just the fact that i don't plan on adding any new features to this, as i don't see too much of a point in it.

**Comment by LucaFlash** [comment]
Looking around the various servers, I think they are features that they all have, but I understand your point of view

Anyway, great script :)

**Comment by vipexv** [comment]
Thank you, hope you have a good day  and i appreciate the discussion!
